### ISSUE TITLE
Store full state in postgres of these two contacts

### ISSUE THREAD

**Issue by mkrump** [vulcanize/vulcanizedb#10]
From AFDudley:

https://etherscan.io/address/0xaec2e87e0a235266d9c5adc9deb4b2e29b54d009
https://etherscan.io/address/0xc78310231aA53bD3D0FEA2F8c705C67730929D8f

For example:
1. Show every to and from transaction that has occurred in these two contracts.
2. Display all the balances of all the accounts associated with the first contract over time.

**Comment by i-norden** [comment]
[account_transformers](https://github.com/vulcanize/account_transformers) provides this feature, more generally.
