### ISSUE TITLE
Process for filling gaps in storage diffs

### ISSUE THREAD

**Issue by rmulhol** [vulcanize/vulcanizedb#123]
If we're fetching diffs off of a pubsub interface then we either need to (1) digest all diffs or (2) digest diffs coming from a specified set of watched contracts.

Digesting all diffs maximizes flexibility but increases resource usage to cache potentially unnecessary data. Digesting diffs from only known watched contracts minimizes resource usage but means that we might miss information emitted before the subscription was setup.

It would be good to have a script for extracting storage diffs that were emitted before a subscription was initiated (e.g. between the deployment block and the first block where a subscription received data).

This could naively be implemented by generating all known storage keys from event data and then querying for `getStorageAt` at all relevant blocks.

**Comment by elizabethengelman** [comment]
@i-norden this work may need to be done on top of https://github.com/vulcanize/vulcanizedb/pull/116. This branch hasn't been merged in yet because we're still waiting for activity on mcd contracts to test out the storage diffing.

**Comment by rmulhol** [comment]
I can see the rationale for deriving backfilled data from the seed node, but I'm also wondering if we might want to have a separate issue on the back burner for backfilling from a standard Eth archive node so that we're not too coupled to our own infra 🤔

**Comment by i-norden** [comment]
The `getStorageAt` approach works but an issue is that it doesn't return diff values but the storage value at every block whether or not it has been updated at that height. We could compensate for this on vulcanizedb's end but it would mean sending a lot of redundant data over the wire only to throw it away. The other option is to add a new RPC method to our custom geth client which returns only diffed values and sub that client in on top of our archival db. Working on that now, but wanted to check in first.

**Comment by rmulhol** [comment]
@i-norden I'm pretty agnostic about how handle this, so I'd say whatever's easiest/seems best to you.

The only caveat I'd add is that I think it'd be good to clearly isolate/document features that depend on node patches that may or may not ever make it upstream, so that we can at least create issues for running those things with a non-patched node

**Comment by i-norden** [comment]
I'm partial to the new RPC method, it's straight forward to add to our geth fork and we already need to use the custom client for state/storage diffing. Also makes it more directly compatible with the packages in #116
