### ISSUE TITLE
Build plugin from Makefile(?)

### ISSUE THREAD

**Issue by rmulhol** [vulcanize/vulcanizedb#128]
Not sure if this is possible, but - related to #127 - it'd be nice if we could separate out some of the parts of building the plugin (e.g. building a .so file) into a `make` command separate from executing the code.

**Comment by grizz** [comment]
I'd take this method vs #127, as it also solves container build problems, and would remove the migrations from the build.

**Comment by i-norden** [comment]
This issue was solved over in the mcd_transformers repository, in that respective makefile.
