### ISSUE TITLE
contractWatcher not marking headers checked

### ISSUE THREAD

**Issue by rmulhol** [vulcanize/vulcanizedb#146]
Still tracking down exactly how this happens, but it seems that the contractWatcher does not always mark all headers as checked while running in header mode. Adding a `MarkHeaderCheckedForAll` after all logs have been processed in `Execute` appears to correct the issue - otherwise the same headers are continually treated as unchecked on subsequent runs.

**Comment by i-norden** [comment]
Need to confirm this but I think this is happening when there are no logs for a contract for the header, but there are for other contracts such that [this](https://github.com/vulcanize/vulcanizedb/blob/staging/pkg/contract_watcher/header/transformer/transformer.go#L254) is hit but [this](https://github.com/vulcanize/vulcanizedb/blob/staging/pkg/contract_watcher/header/transformer/transformer.go#L232) wasn't.
