### ISSUE TITLE
Super node dockerfile/startup_script updates

### ISSUE THREAD

**Issue by i-norden** [vulcanize/vulcanizedb#168]
1. yum install -y libusb1-devel systemd-devel in the build environment in the dockerfile
2. Force vulcanizedb log to stdout (`ln -sf /dev/stdout`)
3. Remove `VDB_PG_CONNECT` since it gets overwritten anyways
4. Use the current dir for vulcanizedb (ADD .)
5. Add flag to make ipfs initialization optional (ipfs throws error if you try to re-initialize)

@grizz if there are any I missed or others you can think of feel free to add them below.

I recall you ran into an error `"msg": "Error loading postgres: db connection failed: pq: no pg_hba.conf entry for host \"127.0.0.1\", user \"ec2-user\", database \"vulcanize_public\", SSL off",`, do you remember if/how you remedied that? Might be more specific to the environment than the dockerfile/startup_script, but would like to make note of it either way.

**Comment by grizz** [comment]
I think that's it, thanks for making the issue.
