### ISSUE TITLE
Create API to View Blocks

### ISSUE THREAD

**Issue by mkrump** [vulcanize/VulcanizeDB#17]
The intent of this is to demonstrate that we can query the blocks using SQL.

Possible options:

Allow users to query for blocks via GraphQL
Present a simple JSON API that executes some hardcoded queries

**Comment by mkrump** [comment]
Added basic graphql backend. Instead of blocks, presenting a view of `watched events` and `filters` tables.

**Comment by AFDudley** [comment]
LGTM.
