### ISSUE TITLE
Smart contract watching configuration file

### ISSUE THREAD

**Issue by AFDudley** [vulcanize/vulcanizedb#18]
Specifies which contract to watch.
Which web3 filters to apply
and other parameters to be determined

**Comment by i-norden** [comment]
@AFDudley I want to say this is covered by the generic `contractWatcher` command and its [configuration file](https://github.com/vulcanize/vulcanizedb/blob/staging/documentation/generic-transformer.md#configuration)

**Comment by rmulhol** [comment]
Closing as the `contractWatcher` does this - can add new tasks for add'l recs
