### ISSUE TITLE
Support these calls via GraphQL

### ISSUE THREAD

**Issue by AFDudley** [vulcanize/vulcanizedb#21]
In large part a documentation issue.
It may be that something in front of GraphQL will be needed here.
Below are examples provided by MakerDAO

Call examples:

http://dai-service.makerdao.com/cups

It brings the actual list of CDPs with their current variables + last block the CDP was updated + if it is closed or not + if it is safe or not.
For this last field we need the actual value of ‘chi’, ‘par’, ‘mat’, ‘per’ and ‘pip’. Some of them can be saved via filters, others need a constant update via intervals due they are dynamically changing per second.

{  
   "lastBlockNumber":4806437,
   "results":[  
      {  
         "_id":"5a428e8ff55dcf743da8b710",
         "cupi":1,
         "lad":"0xcd5f8fa45e0ca0937f86006b9ee8fe1eedee5fc4",
         "ink":0,
         "art":0,
         "ire":0,
         "closed":false,
         "lastBlockNumber":4754490,
         "safe":true
      },
      {  
         "_id":"5a428e8ff55dcf743da8b715",
         "cupi":2,
         "lad":"0x000dcf36d188714ec52fe527d437c486d4fb24d8",
         "ink":1000000000000000000,
         "art":0,
         "ire":0,
         "closed":false,
         "lastBlockNumber":4754510,
         "safe":true
      },
      {  
         "_id":"5a428e8ff55dcf743da8b718",
         "cupi":3,
         "lad":"0x8d44eaae757884f4f8fb4664d07acecee71cfd89",
         "ink":1.2728055128824698e+22,
         "art":3.926421109348261e+24,
         "ire":3.9262374014950224e+24,
         "closed":false,
         "lastBlockNumber":4804048,
         "safe":true
      }
   ]
}

http://dai-service.makerdao.com/cupHistoryActions

{  
   "results":[  
      {  
         "_id":"5a428e8ff55dcf743da8b712",
         "action":"open",
         "cupi":1,
         "sender":"0xcd5f8fa45e0ca0937f86006b9ee8fe1eedee5fc4",
         "param":null,
         "blockNumber":4754490,
         "timestamp":1513602021,
  "transactionHash":"0x53c89dade0a03228ad7312d7f682018b58ad4410df2414410ff3b66993344c54"
      },
      {  
         "_id":"5a428e8ff55dcf743da8b716",
         "action":"open",
         "cupi":2,
         "sender":"0x000dcf36d188714ec52fe527d437c486d4fb24d8",
         "param":null,
         "blockNumber":4754500,
         "timestamp":1513602211,
         "transactionHash":"0x2a10d7adbb584c2dd6beb5d12d06f8afa0062a0757a9be89e084d7e6dc0662ae"
      },
      {  
         "_id":"5a428e8ff55dcf743da8b71a",
         "action":"open",
         "cupi":3,
         "sender":"0x8d44eaae757884f4f8fb4664d07acecee71cfd89",
         "param":null,
         "blockNumber":4754500,
         "timestamp":1513602211,
         "transactionHash":"0x18bd197d83c62c6de70512dc18842748b27ffff98d9e0b0c6ab0278b127c096f"
      }
   ]
}

**Comment by desaperados** [comment]
I've drafted a GraphQL schema definition which broadly covers the kinds of calls we'll be looking for. Can develop this further once I have a better understanding of what will be available from the postgres view:

https://gist.github.com/desaperados/cc0d67d72656b5e36fb3db68d351a8c9

**Comment by desaperados** [comment]
I guess the trick is going to be figuring out how to define the necessary filters, views and GraphQL schema via a config file. I'm thinking of building a concrete solution for the Dai contracts as an exercise - web3 filters writing to a dai Postgres schema with a GraphQL implementation which could be used as reference for a more generic solution.

**Comment by mkrump** [comment]
@desaperados right now we are storing the event filters in their encoded form (and requiring that they be specified that way in the config as well). For example, filtering on a specific event via web3

```
tub.LogNote({ sig: methodSig('mold(bytes32,uint256)'), foo: '0x6d61740000000000000000000000000000000000000000000000000000000000' }, { fromBlock }
```

Generates a filter like below. So we are just storing the encoded filter and using that to select the matching logs.

```
var filterOptions = {
      "toBlock": "latest",
      "fromBlock": "0x488290",
      "address": "0x448a5065aebb8e423f0896e6c5d525c040f59af3",
      "topics": ["0x92b0d72100000000000000000000000000000000000000000000000000000000", null, "0x6d61740000000000000000000000000000000000000000000000000000000000", null]
};
```

Also, we were thinking the view of watched events would present the encoded logs as well, but if an abi was available we’d populate a column with a json version of the decoded log as well. This would hopefully avoid having to create a new postgres schema per event. 

As an aside, should we invite the relevant maker people to a Slack channel so we can talk in something closer to real time?

**Comment by desaperados** [comment]
Hi @mkrump - a real time channel is a good idea. I'd like to discuss how log events can be used to populate the state that we're interested in tracking. I'm `dc` at chat.makerdao.com - if you join there we can set up a channel, or can join your Slack if you prefer.

**Comment by mkrump** [comment]
https://chat.makerdao.com is good. Signed up `matt.k` and co-worker is `gustin`. I didn't see you when I checked this afternoon. Is there a good time to stop by (we're located in CST)?

**Comment by rmulhol** [comment]
Closing because we're working off of https://github.com/makerdao/vulcan.spec now
