### ISSUE TITLE
Store snapshot of contract's history on IPFS

### ISSUE THREAD

**Issue by rmulhol** [vulcanize/vulcanizedb#30]
As an application developer using vulcanize to track the history of my contract,
I want to be able to upload a snapshot of that contract's full history to IPFS,
So that I can share that info with others, in particular the end-users of my application.

Notes
- Focus is on persisting data sourced from VulcanizeDB on a distributed network
- Brackets questions of how to trustlessly validate that history and setup gossiping

**Comment by AFDudley** [comment]
I made my edits above. Thanks.

**Comment by rmulhol** [comment]
Closing as this is at least partially addressed with `syncAndPublish`. Can reopen and/or create a new issue if there are additional requirements
