### ISSUE TITLE
Handler Boilerplate

### ISSUE THREAD

**Issue by rmulhol** [vulcanize/vulcanizedb#35]
As a VulcanizeDB application developer,
I want to be able to clone a handler boilerplate repo,
So that I can get to work writing my own handlers with minimal setup.

**Comment by i-norden** [comment]
I think this is covered by the [composeAndExecute](https://github.com/vulcanize/vulcanizedb/blob/staging/documentation/composeAndExecute.md) functionality?? Terminology has changed since this issue was opened, and I'm not sure what handler means.

**Comment by rmulhol** [comment]
Yeah agreed - I basically meant transformer boilerplate. But between example transformers and the `contractWatcher` I'm going to close
