### ISSUE TITLE
ERC20 Transformer

### ISSUE THREAD

**Issue by rmulhol** [vulcanize/vulcanizedb#49]
As an application developer running VulcanizeDB,
I want to be able to identify ERC20 contracts and persist that they exist,
So that I have an inventory of ERC20 contracts from which to perform further work.

As an application developer running VulcanizeDB,
I want to persist data fetched from queries against ERC20 contract,
So that I have a record of the contract's state.

**Notes**
For the first pass, focus queries against ERC20 contracts on the methods defined by the interface.

**Comment by elizabethengelman** [comment]
further notes/clarification:

1. a suite of transformers:
    - find all ERC20 contracts (ABI analysis; search blockchain for ERC20 tokens; be able to find unregistered ones; scan contracts by interface)
    - store data for every ERC20 contract
    - a way for a user to configure a new transformer - would this be for a specific contract?

2. a separate script, that once you've found the address of the contract you want, pull the rest of the information from etherscan (for those that are registered)

3. UI
  - graphql endpoint
  - select a particular ERC20 contract from a list
  - search for an ERC20 contract (by address?)
  - be able to access the following information about a contract:
      - balance history
      - account balance at a particular height (the result should have a CID?)

*points 2 and 3 can be broken out into different issues going forward

**Comment by elizabethengelman** [comment]
2 things:
1. Given an address:
  - confirm that it is an ERC20 token
  - be able to get additional information about it (i.e. account history of the token)

2. specify an array of bytes that you want to find in the storage trie (over ranges of old blocks, and incoming blocks)

**Comment by elizabethengelman** [comment]
[x] transformer for totalSupply function
[  ] Transfer event
[  ] transformer for balanceOf function
        - balanceOf requires an owner address to passed in, so we potentially will need a list of all token holders
        - to get the list of all token holders, we probably need to watch for all of the Transfer events on the token
        - or inspect the contract's mapping, and decode this
[  ] transfer function
[  ] approve function
[  ] allowance function
[  ] Approval event
[  ] given an address, check if it is an ERC20 contract

**Comment by i-norden** [comment]
I believe the generic `contractWatcher` can provide all of this functionality except for the `given and address, check if it is an ERC20 contract` bit.

**Comment by i-norden** [comment]
But given the new framework, it seems like this is now an issue for a specific transformer, so I think it safe to close this?

**Comment by i-norden** [comment]
@elizabethengelman OK to close this issue? Generic `contractWatcher` provides most of this functionality, and I think this is generally out of scope for this repo and more appropriate to a specific transformer's repo instead now.

**Comment by i-norden** [comment]
@rmulhol realizing now this was opened by you and not Elizabeth. Per my above comments, do you think we can close this?

**Comment by rmulhol** [comment]
@i-norden yep 👍
