### ISSUE TITLE
Generate Queries for Log data

### ISSUE THREAD

**Issue by mkrump** [vulcanize/vulcanizedb#5]
The current [sai-service](https://github.com/makerdao/sai-service), monitors events (via the logs) for a series of contracts. The ethereum logs capture events emitted by the ethereum VM. The logs have the following format:

```
{
    address: "0x448a5065aebb8e423f0896e6c5d525c040f59af3",
    blockHash: "0xe627181ae6bf9835066077235ae14aa75a54e8018ac116508f783850200c15c5",
    blockNumber: 4752015,
    data: "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000004492b0d72163617000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
    logIndex: 40,
    removed: false,
    topics: ["0x92b0d72100000000000000000000000000000000000000000000000000000000", "0x000000000000000000000000f07674f6ac6632e253c291b694f9c2e2ed69ebbb", "0x6361700000000000000000000000000000000000000000000000000000000000", "0x0000000000000000000000000000000000000000000000000000000000000000"],
    transactionHash: "0x80c8375c679404f73833f36be0d2903c4931764827da2a323d8ba83749c20715",
    transactionIndex: 71
}
```
The various topics are indexed allowing for fast retrieval. Typically the topics are encoded as follows ([https://ethereum.stackexchange.com/questions/12553/understanding-logs-and-log-blooms](https://ethereum.stackexchange.com/questions/12553/understanding-logs-and-log-blooms)): 
 - topic0: The hex encoded sha3 hash of the method signature (e.g. `web3.sha3("LogValue(bytes32)")`)
 - topics 1-3: represent the remaining indexed event parameters abi encoding [https://github.com/ethereum/wiki/wiki/Ethereum-Contract-ABI](https://github.com/ethereum/wiki/wiki/Ethereum-Contract-ABI)
- data: contains the remaining non-indexed abi encoded event parameters concatenated together.

However, it does seem that this format can be overridden. sai-service for example watches for LogNote events. These seem to be custom logging events that don't necessarily adhered to the convention described above (need to clarify this is correct) (solidity code below).

```
////// lib/ds-thing/lib/ds-note/src/note.sol
/// note.sol -- the `note' modifier, for logging calls as events
contract DSNote {
    event LogNote(
        bytes4   indexed  sig,
        address  indexed  guy,
        bytes32  indexed  foo,
        bytes32  indexed  bar,
        uint              wad,
        bytes             fax
    ) anonymous;

    modifier note {
        bytes32 foo;
        bytes32 bar;

        assembly {
            foo := calldataload(4)
            bar := calldataload(36)
        }

        LogNote(msg.sig, msg.sender, foo, bar, msg.value, msg.data);

        _;
    }
}
``` 

Right now we have several potential ways to capture logs for a particular address, so how to do this is clear. The part that is uncertain will be how to generate the queries for contracts events of interest. Right now (for sai-service) the generation of the filters (queries) is done via the `web3` api.

```
tub.LogNote({ sig: methodSig('mold(bytes32,uint256)'), foo: '0x6d61740000000000000000000000000000000000000000000000000000000000' }, { fromBlock }
```
generates the following filter
```
var filterOptions = {
      "toBlock": "latest",
      "fromBlock": "0x488290",
      "address": "0x448a5065aebb8e423f0896e6c5d525c040f59af3",
      "topics": ["0x92b0d72100000000000000000000000000000000000000000000000000000000", null, "0x6d61740000000000000000000000000000000000000000000000000000000000", null]
};
```
Recreating this mapping from ABI to filters (or including via `go` or maybe `web3`) is likely required for users to be able to retrieve events in a way that is meaningful to them.

**Comment by rmulhol** [comment]
Closing as the `contractWatcher` is capable of generating lookups most of the time, and bespoke transformers can otherwise embed the custom logic
