### ISSUE TITLE
Update vulcanize to properly handle dep's issue with case insensitivity (for github repos)

### ISSUE THREAD

**Issue by elizabethengelman** [vulcanize/vulcanizedb#59]
Based on https://github.com/golang/dep/issues/433 it seems that dep is not able to handle case insensitivity, specifically with github. This is causing some weird behavior in VDB, like adding VulcanizeDB into it's own vendor directory.

Steps to reproduce:
- clone the project
- cd into the `VulcanizeDB` directory that was created
- run `dep ensure`
- notice that "github.com/vulcanize/vulcanizedb" is added to `Gopkg.lock` as a dependency
- if you make a change to your local VulcanizeDB project (i.e. add an extra print statement to the `sync` command) and then rebuild, the change you've made will not be reflected. I think that this is because the binary that is created is using the "vendored vulcanize db" instead 

A quick fix is to locally change the `VulcanizeDB` directory to `vulcanizedb` (no capitals), but we should instead figure out a better way to handle this - perhaps changing the repo name would help, but maybe there is another solution.

**Comment by AFDudley** [comment]
Please confirm the name changed fixed this issue, thanks.

**Comment by elizabethengelman** [comment]
The repo name change seemed to fix this issues, so I'll close this issue. Thanks!
