### ISSUE TITLE
Create state trie extractor

### ISSUE THREAD

**Issue by mkrump** [vulcanize/vulcanizedb#6]
From AFDudley:

The details of this need to be fleshed out a bit. But the general idea is we should create a tool for moving state trie data around. It should:
1. extract state trie data from a geth leveldb
    a. as JSON blobs
    b. as IPLD (maybe CBOR) blobs
    c. as some other efficient format.
2. inject state trie data into a geth leveldb
3. inject state trie data into IPFS (in support of https://github.com/paritytech/parity/issues/4172)
4. inject state trie data into our postgres DB (if we do 3 I think we can skip this.)

**Comment by AFDudley** [comment]
@rmulhol this can be closed, right?

**Comment by rmulhol** [comment]
Subtasks 1.b and 3 are accomplished by [this PR](https://github.com/vulcanize/block_watcher/pull/9). The other tasks remain to be done, if we still want to do them.

**Comment by rmulhol** [comment]
Closing as we've broken this out into work on a Geth patch + `syncAndPublish` being overseen by @i-norden
