### ISSUE TITLE
Repair geth databases

### ISSUE THREAD

**Issue by mkrump** [vulcanize/vulcanizedb#7]
Write a tool based on the work done in #121 to inject missing state trie information into a geth leveldb.

**Comment by AFDudley** [comment]
@rmulhol can this closed?

**Comment by rmulhol** [comment]
I don't think I'd close it out just yet. There's still work to be done in terms of fetching and persisting missing state trie info. That said, we should be able to leverage the data generated by [this PR](https://github.com/vulcanize/block_watcher/pull/9) to accomplish that.

**Comment by rmulhol** [comment]
Closing as this line of work will probably be carried out in vulcanize/go-ethereum if we tackle it
