### ISSUE TITLE
Improve the efficiency of receipts retrieval for a block

### ISSUE THREAD

**Issue by mkrump** [vulcanize/vulcanizedb#8]
Right now we're retrieving the receipts using the ethereum client's `TransactionReceipt` method. This requires retrieving the receipts one at a time over the RPC. This is obviously slow and inefficient. Ideally we'd retrieve all receipts in bulk for a given block. Two avenues worth exploring are:

1) `GetBlockReceipts` in `ethereum/go-ethereum/core/database_util.go`. This appears to be what we'd need. The downside of this method is that we'd no longer be able to use the RPC connection and instead would need a connection to the leveldb. This would probably mean using Infura or similar services served over RPC would no longer be possible.

2) `ethereum/go-ethereum/eth/api_backend.go` also wraps the`database_utils.go` `GetBlockReceipts` method. This would have a similar set of cons as above. The advantage here is that the eth node could be started programatically.

**Comment by mkrump** [comment]
Below is an example of using the database_utils.go API. `NewLDBDatabase` doesn't work if the DB is already open though, so would need to figure out how to connect to running db.

```
package main

import (
	"fmt"

	"log"

	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/core"
	"github.com/ethereum/go-ethereum/ethdb"
)

func main() {
	db, err := ethdb.NewLDBDatabase("/Users/mattkrump/Library/Ethereum/geth/chaindata", 128, 1024)
	if err != nil {
		log.Fatal(err)
	}
	blockHash := common.HexToHash("0x9007a031deb993870d7a2b7732ee50089e281411de275bbfaf02f6896ced574c")
	blockNumber := uint64(4854746)

	block := core.GetBlock(db, blockHash, blockNumber)
	fmt.Println(block)

	txHash := common.HexToHash("0x56f6f0fd7f1c7996fc8828a76fa99a58812f7af590d3f9fbdc465020dd865cf0")
	transaction, blockHash, blockNumber, txIndex := core.GetTransaction(db, txHash)
	fmt.Println(transaction.Hash().Hex())
	fmt.Println(blockHash)
	fmt.Println(blockNumber)
	fmt.Println(txIndex)

	receipts := core.GetBlockReceipts(db, blockHash, blockNumber)
	fmt.Println(len(receipts))
	for _, receipt := range receipts {
		fmt.Println(receipt)
	}
}
```

**Comment by mkrump** [comment]
From AFDudley:

1. is good for me.

We will want to be able to "repair" geth databases by injecting state trie data. We can also use similar code to pull the state trie data we have and place it into postgres.

**Comment by i-norden** [comment]
I think we can close this, as I understand it the seed node provides analogous functionality: it streams out state and storage diffs + block data and receipts in a single payload at each block; it is using the `GetBlockReceipts` method under the hood, but with the state diffing service API everything is sent over RPC.

**Comment by i-norden** [comment]
@rmulhol do you think this can be closed per the above comment?

**Comment by rmulhol** [comment]
@i-norden 👍

**Comment by i-norden** [comment]
Closing per the above :)
