### ISSUE TITLE
postgraphile requires webpack installed globally

### ISSUE THREAD

**Issue by ramilexe** [vulcanize/vulcanizedb#87]
`yarn build` call webpack https://github.com/vulcanize/vulcanizedb/blob/staging/postgraphile/package.json#L6 and it should be installed globally. There is no in documentation about it. 
I suggest to call webpack from `node_modules/.bin/webpack`

**Comment by i-norden** [comment]
This issue has been deprecated since we removed internal postgraphile support and instead defer to using the postgraphile CLI. Thank you for highlighting this problem @ramilexe!
